'use server';
import { Company } from '@/types/types';
const PLATFORM_API_BASE_URL = process.env.PLATFORM_API_BASE_URL;

const COMPANIES_URLS = {
  allPromotedCompanies: `${PLATFORM_API_BASE_URL}/api/v1/companies/promoted`,
  singleCompany: `${PLATFORM_API_BASE_URL}/api/v1/companies`,
};
const companies: Company[] = [
  {
    name: 'Fake Company 1',
    country: 'Fake Country',
    city: 'Fake City',
    logo_url: '/assets/icons/companies/example-logo-1.png',
    website: 'https://fake-company.com',
    contact_name: null,
    email: null,
    phone_number: null,
    company_size: null,
    social_media_links: null,
    promoted: false,
    promotion_duration_days: null,
    promotion_ends: null,
    id: 1,
    recruiters: null,
    created: null,
    updated: null,
  },
  {
    name: 'Fake Company 2',
    country: 'Fake Country',
    city: 'Fake City',
    logo_url: '/assets/icons/companies/example-logo-2.png',
    website: 'https://fake-company.com',
    contact_name: null,
    email: null,
    phone_number: null,
    company_size: null,
    social_media_links: null,
    promoted: false,
    promotion_duration_days: null,
    promotion_ends: null,
    id: 2,
    recruiters: null,
    created: null,
    updated: null,
  },
  {
    name: 'Fake Company 3',
    country: 'Fake Country',
    city: 'Fake City',
    logo_url: '/assets/icons/companies/example-logo-3.png',
    website: 'https://fake-company.com',
    contact_name: null,
    email: null,
    phone_number: null,
    company_size: null,
    social_media_links: null,
    promoted: false,
    promotion_duration_days: null,
    promotion_ends: null,
    id: 3,
    recruiters: null,
    created: null,
    updated: null,
  },
  {
    name: 'Fake Company 4',
    country: 'Fake Country',
    city: 'Fake City',
    logo_url: '/assets/icons/companies/example-logo-4.png',
    website: 'https://fake-company.com',
    contact_name: null,
    email: null,
    phone_number: null,
    company_size: null,
    social_media_links: null,
    promoted: false,
    promotion_duration_days: null,
    promotion_ends: null,
    id: 4,
    recruiters: null,
    created: null,
    updated: null,
  },
  {
    name: 'Fake Company 5',
    country: 'Fake Country',
    city: 'Fake City',
    logo_url: '/assets/icons/companies/example-logo-5.png',
    website: 'https://fake-company.com',
    contact_name: null,
    email: null,
    phone_number: null,
    company_size: null,
    social_media_links: null,
    promoted: false,
    promotion_duration_days: null,
    promotion_ends: null,
    id: 5,
    recruiters: null,
    created: null,
    updated: null,
  },
  {
    name: 'Fake Company 6',
    country: 'Fake Country',
    city: 'Fake City',
    logo_url: '/assets/icons/companies/example-logo-6.png',
    website: 'https://fake-company.com',
    contact_name: null,
    email: null,
    phone_number: null,
    company_size: null,
    social_media_links: null,
    promoted: false,
    promotion_duration_days: null,
    promotion_ends: null,
    id: 6,
    recruiters: null,
    created: null,
    updated: null,
  },
  {
    name: 'Fake Company 7',
    country: 'Fake Country',
    city: 'Fake City',
    logo_url: '/assets/icons/companies/example-logo-7.png',
    website: 'https://fake-company.com',
    contact_name: null,
    email: null,
    phone_number: null,
    company_size: null,
    social_media_links: null,
    promoted: false,
    promotion_duration_days: null,
    promotion_ends: null,
    id: 7,
    recruiters: null,
    created: null,
    updated: null,
  },
  {
    name: 'Fake Company 8',
    country: 'Fake Country',
    city: 'Fake City',
    logo_url: '/assets/icons/companies/example-logo-8.png',
    website: 'https://fake-company.com',
    contact_name: null,
    email: null,
    phone_number: null,
    company_size: null,
    social_media_links: null,
    promoted: false,
    promotion_duration_days: null,
    promotion_ends: null,
    id: 8,
    recruiters: null,
    created: null,
    updated: null,
  },
  {
    name: 'Fake Company 9',
    country: 'Fake Country',
    city: 'Fake City',
    logo_url: '/assets/icons/companies/example-logo-9.png',
    website: 'https://fake-company.com',
    contact_name: null,
    email: null,
    phone_number: null,
    company_size: null,
    social_media_links: null,
    promoted: false,
    promotion_duration_days: null,
    promotion_ends: null,
    id: 9,
    recruiters: null,
    created: null,
    updated: null,
  },
  {
    name: 'Fake Company 10',
    country: 'Fake Country',
    city: 'Fake City',
    logo_url: '/assets/icons/companies/example-logo-10.png',
    website: 'https://fake-company.com',
    contact_name: null,
    email: null,
    phone_number: null,
    company_size: null,
    social_media_links: null,
    promoted: false,
    promotion_duration_days: null,
    promotion_ends: null,
    id: 10,
    recruiters: null,
    created: null,
    updated: null,
  },
  {
    name: 'Fake Company 11',
    country: 'Fake Country',
    city: 'Fake City',
    logo_url: '/assets/icons/companies/example-logo-11.png',
    website: 'https://fake-company.com',
    contact_name: null,
    email: null,
    phone_number: null,
    company_size: null,
    social_media_links: null,
    promoted: false,
    promotion_duration_days: null,
    promotion_ends: null,
    id: 11,
    recruiters: null,
    created: null,
    updated: null,
  },
  {
    name: 'Fake Company 12',
    country: 'Fake Country',
    city: 'Fake City',
    logo_url: '/assets/icons/companies/example-logo-12.png',
    website: 'https://fake-company.com',
    contact_name: null,
    email: null,
    phone_number: null,
    company_size: null,
    social_media_links: null,
    promoted: false,
    promotion_duration_days: null,
    promotion_ends: null,
    id: 12,
    recruiters: null,
    created: null,
    updated: null,
  },
  {
    name: 'Fake Company 13',
    country: 'Fake Country',
    city: 'Fake City',
    logo_url: '/assets/icons/companies/example-logo-13.png',
    website: 'https://fake-company.com',
    contact_name: null,
    email: null,
    phone_number: null,
    company_size: null,
    social_media_links: null,
    promoted: false,
    promotion_duration_days: null,
    promotion_ends: null,
    id: 13,
    recruiters: null,
    created: null,
    updated: null,
  },
  {
    name: 'Fake Company 14',
    country: 'Fake Country',
    city: 'Fake City',
    logo_url: '/assets/icons/companies/example-logo-14.png',
    website: 'https://fake-company.com',
    contact_name: null,
    email: null,
    phone_number: null,
    company_size: null,
    social_media_links: null,
    promoted: false,
    promotion_duration_days: null,
    promotion_ends: null,
    id: 14,
    recruiters: null,
    created: null,
    updated: null,
  },
  {
    name: 'Fake Company 15',
    country: 'Fake Country',
    city: 'Fake City',
    logo_url: '/assets/icons/companies/example-logo-15.png',
    website: 'https://fake-company.com',
    contact_name: null,
    email: null,
    phone_number: null,
    company_size: null,
    social_media_links: null,
    promoted: false,
    promotion_duration_days: null,
    promotion_ends: null,
    id: 15,
    recruiters: null,
    created: null,
    updated: null,
  },
  {
    name: 'Fake Company 16',
    country: 'Fake Country',
    city: 'Fake City',
    logo_url: '/assets/icons/companies/example-logo-16.png',
    website: 'https://fake-company.com',
    contact_name: null,
    email: null,
    phone_number: null,
    company_size: null,
    social_media_links: null,
    promoted: false,
    promotion_duration_days: null,
    promotion_ends: null,
    id: 16,
    recruiters: null,
    created: null,
    updated: null,
  },
  {
    name: 'Fake Company 17',
    country: 'Fake Country',
    city: 'Fake City',
    logo_url: '/assets/icons/companies/example-logo-17.png',
    website: 'https://fake-company.com',
    contact_name: null,
    email: null,
    phone_number: null,
    company_size: null,
    social_media_links: null,
    promoted: false,
    promotion_duration_days: null,
    promotion_ends: null,
    id: 17,
    recruiters: null,
    created: null,
    updated: null,
  },
  {
    name: 'Fake Company 18',
    country: 'Fake Country',
    city: 'Fake City',
    logo_url: '/assets/icons/companies/example-logo-18.png',
    website: 'https://fake-company.com',
    contact_name: null,
    email: null,
    phone_number: null,
    company_size: null,
    social_media_links: null,
    promoted: false,
    promotion_duration_days: null,
    promotion_ends: null,
    id: 18,
    recruiters: null,
    created: null,
    updated: null,
  },
  {
    name: 'Fake Company 19',
    country: 'Fake Country',
    city: 'Fake City',
    logo_url: '/assets/icons/companies/example-logo-19.png',
    website: 'https://fake-company.com',
    contact_name: null,
    email: null,
    phone_number: null,
    company_size: null,
    social_media_links: null,
    promoted: false,
    promotion_duration_days: null,
    promotion_ends: null,
    id: 19,
    recruiters: null,
    created: null,
    updated: null,
  },
  {
    name: 'Fake Company 20',
    country: 'Fake Country',
    city: 'Fake City',
    logo_url: '/assets/icons/companies/example-logo-20.png',
    website: 'https://fake-company.com',
    contact_name: null,
    email: null,
    phone_number: null,
    company_size: null,
    social_media_links: null,
    promoted: false,
    promotion_duration_days: null,
    promotion_ends: null,
    id: 20,
    recruiters: null,
    created: null,
    updated: null,
  },
];
export async function getPromotedCompanies(): Promise<Company[]> {
  return companies;
}
export async function getCompanyById(companyId: string | number): Promise<Company> {
  if (!companyId) {
    // can return 404 heres
    return {} as Company;
  }
  const company = companies.find((comp) => comp.id.toString() === companyId);
  if (company) return company;
  return {} as Company;
}
