type JobData = {
  id: number;
  language: string;
  title: string;
  isHot: boolean;
  external_company_name: string | null;
  employment_type: string;
  experienceRequired: string;
  location: string;
  salary: string;
  applications: number;
  datePosted: string;
  description: string;
  skill_tags: string[];
  external_job_id: null | number;
  external_company_id: null | number;
  external_company_logo: null | string;
  external_feed_id: null | number;
  external_source: null | string;
  external_extra_1: null | string;
  external_extra_2: null | string;
  external_extra_3: null | string;
  external_company_website: null | string;
  external_company_industry: null | string;
  external_company_established: null | string;
  external_company_size: null | number | string;
  city: string;
  country: string;
  work_location_type: string;
  remuneration_from: number | null;
  remuneration_to: number | null;
  remuneration_currency: string;
  short_description: string;
  job_requirements: string;
  welcomed_skills: string;
  is_hot: boolean;
  is_external: boolean;
  external_link: string | null;
  id_parent_job_translation: string | null | number;
  parent_language: null | string;
  category: {
    id: number;
    name: string;
  };
  latitude: string | number | null;
  longitude: string | null | number;
  is_added_to_qdrant: boolean;
  geo_resolve_tries: number | null;
  is_dummy: boolean;
  created: string;
  updated: string;
  applicants: number;
  viewed: number;
};
